name: py:pre-release

on:
  push:
    tags: 'v*'

jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout commit
      uses: actions/checkout@v4
    - name: Get the Git tag name
      id: get-tag-name
      run: echo "tag-name=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_OUTPUT"
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get-tag-name.outputs.tag-name }}
        release_name: v${{ steps.get-tag-name.outputs.tag-name }}
        body: |-
          "ppt_json" release v${{ steps.get-tag-name.outputs.tag-name }}
        prerelease: true
