name: py:publish

on:
  release:
    types: [ released ]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ppt_json
    env:
      PPT_VERSION: ''
    permissions:
      id-token: write

    steps:
    - name: Checkout commit
      uses: actions/checkout@v4
    - name: Set env PPT_VERSION
      run: echo "PPT_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_ENV"
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install build dependency
      run: |-
        pip install build
    - name: Execute build
      run: |-
        python -m build --sdist --wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
